# Generated by Django 4.0.5 on 2022-06-17 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=1500)),
                ('first_name', models.CharField(max_length=1500)),
                ('last_name', models.CharField(max_length=1500)),
                ('email', models.EmailField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=1500)),
                ('product_price', models.IntegerField()),
                ('purchased_date', models.DateField(auto_now_add=True)),
                ('buyers', models.ManyToManyField(to='medicalblog.people')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=1500)),
                ('doctor_contact', models.IntegerField()),
                ('patients_name', models.ManyToManyField(to='medicalblog.people')),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1500)),
                ('bio', models.TextField(max_length=10000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medicalblog.people')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1500)),
                ('street_address', models.CharField(max_length=1500)),
                ('city', models.CharField(max_length=1500)),
                ('State', models.CharField(max_length=1500)),
                ('country', models.CharField(max_length=1500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalblog.people')),
            ],
        ),
    ]
